### PR TITLE
fix: update to the latest version of the SDK

### PR DESCRIPTION
**Pull request by wtrocki**
This PR adjusts version of the SDK to the latests. 
When adjusting I found out numerous cases where we have incompatible enums defined in the ui-components. 
I have marked those areas with TODO to get some explanation from core team

### CODE REVIEW

**Comment by wtrocki** [comment]
I know what is happening. It looks like we got more enums from SDK and the ones we had defined in UI outdated/do not match the ones on SDK.
I will remove enums from UI and use SDK ones from now

**Comment by wtrocki** [comment]
We have number of enums now returned by the SDKs that weren't returned before
as result we getting a lot of incompatibilities between what is in the `@rhoas/app-services-ui-shared` and actual types returned by SDKs

There are couple ways to solve it:

1) Manually adjust types that we have in the  rhoas/app-services-ui-shared - In some cases we will be fixing obvious bugs related to lack of typescript validation when dev was done

2) Add kafka-sdk to app-services-ui-shared and use underlying enums in events/modaltypes etc.

3) Move kafka type of the logic from app-services-ui-shared back to the Kafka-UI (they seem specific)

**Comment by ajaypratap003** [comment]
> We have number of enums now returned by the SDKs that weren't returned before as result we getting a lot of incompatibilities between what is in the `@rhoas/app-services-ui-shared` and actual types returned by SDKs
> 
> There are couple ways to solve it:
> 
> 1. Manually adjust types that we have in the  rhoas/app-services-ui-shared - In some cases we will be fixing obvious bugs related to lack of typescript validation when dev was done

This is not ideal but we ca fix issues for now temporary 

> 2. Add kafka-sdk to app-services-ui-shared and use underlying enums in events/modaltypes etc.

 This option is straight forward and permanent solution if there is not any concern.

> 3. Move kafka type of the logic from app-services-ui-shared back to the Kafka-UI (they seem specific)

We can move kafka type of logic back to kafka-ui but it will be bit major changes . There are some common logic related to modals logic used in multiple modules kas-ui, kafka-ui, srs-ui etc. 

Similarly we copied some types (acls types) in ui-components repo due to concern of using kafka-sdk. 

Let's discuss more about it offline.

**Comment by riccardo-forina** [comment]
> Similarly we copied some types (acls types) in ui-components repo due to concern of using kafka-sdk.

This was not the correct thing to do. The rule of not depending on the SDKs on the shared repos is there exactly to avoid this kind of issues. The right thing to do would have been to figure out which data the UI needed to do its job and make that the exported type. 
After having done that, in the apps (kafka-ui, kas-ui, etc) we would have written the code required to translate the data coming from the SDKs to the data required by the UI.

In other words, we need to build layers and the code to connect them.  I have asked for an ADR I'd to document this but I don't have one yet. A short description of the layers from the top to the bottom would be:

* ui-components - this deals with the visuals. The data is thought in terms of text the user will see. User actions that manipulate the data (delete, save) trigger callbacks that will be handled in a lower layer
* (kafka|kas|srs|...)-ui - this layer contains the code that interacts with the SDKs to gather the data required by the UI. It also deals with the routes owned by the app. It's bootstrapped with props coming from the lower layer for actions that are common across all apps (like showing a notification or opening a drawer) plus the data required to work with the SDKs (URLs, tokens, etc).
At least one federated module is exposed by this layer, the app itself. More can be exposed if a feature is expected to be used across services (eg. the Kafka creation dialog).
* app-services-ui - the lower layer. It implements features common across the services (eg. a drawer), it deals with the authentication, it deals with the configs and it mounts all the apps on their allotted route, passing them the data required for them to work. It can use the SDKs to figure what kind of features the user has access to.

**Comment by riccardo-forina** [comment]
About the problem at hand, we already discussed offline and defined this order of actions:

1. enable TS on kafka-ui and kas-ui
2. remove these clashing types from the shared repo, which means decoupling the modals from the SDK
3. update kafka-ui and kas-ui to use the new shared repo
4. upgrade the SDKs on kafka-ui and kas-ui

Each point is a single PR that will have to be validated against the test suite on stage

**Comment by riccardo-forina** [comment]
Superseded by #700

**Pull request closed without merging**
